In [2]:
import numpy as np

<div><h1 style = "color:cyan"><b>Numpy Array Operation: SLICING</h1><div>

## Slicing Operation on 1D-Array:

In [3]:
arr_1d = np.array([10, 20, 30, 40, 50], dtype="int32")

print("Basic Slicing", arr_1d[1:4])          # Output: [20 30 40]
print("Slicing with Step", arr_1d[0:5:2])  # Output: [10 30 50]
print("Negative Indices", arr_1d[-4:-1])   # Output: [20 30 40]

print("Omitting Start Index", arr_1d[:3])  # Output: [10 20 30]
print("Omitting End Index", arr_1d[2:])    # Output: [30 40 50]

print("Full Array", arr_1d[:])              # Output: [10 20 30 40 50]
# Demonstrating various slicing techniques on a 1D NumPy array



Basic Slicing [20 30 40]
Slicing with Step [10 30 50]
Negative Indices [20 30 40]
Omitting Start Index [10 20 30]
Omitting End Index [30 40 50]
Full Array [10 20 30 40 50]


## Slicing Operation on 2D-Array:

In [4]:
arr_2d = np.array([
    [10, 20, 30], 
    [40, 50, 60], 
    [70, 80, 90]], dtype="int32")

print("Specific Element Access:", arr_2d[1, 2])  # Output: 60

print("2D Array Slicing - Rows 0 to 1, All Columns:\n", arr_2d[0:2, :])
# Output: [[10 20 30]
#          [40 50 60]]
print("2D Array Slicing - All Rows, Columns 1 to 2:\n", arr_2d[:, 1:3])
# Output: [[20 30]
#          [50 60]
#          [80 90]]
print("2D Array Slicing - Rows 1 to End, Columns 0 to 1:\n", arr_2d[1:, 0:2])
# Output: [[40 50]
#          [70 80]]

print("2D Array Slicing - Full Array:\n", arr_2d[:, :])
# Output: [[10 20 30]   
#          [40 50 60]
#          [70 80 90]]



Specific Element Access: 60
2D Array Slicing - Rows 0 to 1, All Columns:
 [[10 20 30]
 [40 50 60]]
2D Array Slicing - All Rows, Columns 1 to 2:
 [[20 30]
 [50 60]
 [80 90]]
2D Array Slicing - Rows 1 to End, Columns 0 to 1:
 [[40 50]
 [70 80]]
2D Array Slicing - Full Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


## Slicing Operation 3D-Array

In [5]:
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]], dtype="int32")

print("Specific Element Access in 3D Array:", arr_3d[1, 0, 2])  # Output: 9
print("3D Array Slicing - First Two 2D Arrays, All Rows, All Columns:\n", arr_3d[0:2, :, :])
# Output: [[[ 1  2  3]
#          [ 4  5  6]]
#         [[ 7  8  9]
#          [10 11 12]]]

print("3D Array Slicing - All 2D Arrays, First Row, All Columns:\n", arr_3d[:, 0, :])
# Output: [[ 1  2  3]
#          [ 7  8  9]
#          [13 14 15]]
print("3D Array Slicing - All 2D Arrays, All Rows, First Two Columns:\n", arr_3d[:, :, 0:2])
# Output: [[[ 1  2]
#          [ 4  5]]
#         [[ 7  8]
#          [10 11]]
#         [[13 14]
#          [16 17]]]
print("3D Array Slicing - Full Array:\n", arr_3d[:, :, :])
# Output: [[[ 1  2  3]
#          [ 4  5  6]]
#         [[ 7  8  9]
#          [10 11 12]]
#         [[13 14 15]
#          [16 17 18]]]


Specific Element Access in 3D Array: 9
3D Array Slicing - First Two 2D Arrays, All Rows, All Columns:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3D Array Slicing - All 2D Arrays, First Row, All Columns:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
3D Array Slicing - All 2D Arrays, All Rows, First Two Columns:
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]
3D Array Slicing - Full Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


<div><h1 style = "color:cyan"><b>Numpy Array Operation: SORTING</h1><div>

## Sorting on 1D-Array:

In [6]:
unsorted_arr = np.array([50, 20, 40, 10, 30, 10,3,1,100,99], dtype="int32")

print("Sorted Array:", np.sort(unsorted_arr))
print("Original Unsorted Array:", unsorted_arr)

arr_strings = np.array(["banana", "apple", "cherry", "date"], dtype="U10")
print("Sorted String Array:", np.sort(arr_strings))
print("Original String Array:", arr_strings)

arr_float = np.array([3.1, 2.4, 5.6, 1.2, 4.8], dtype="float32")
print("Sorted Float Array:", np.sort(arr_float))
print("Original Float Array:", arr_float)

# .sort() function returns a sorted copy of the array without modifying the original array
# .argsort() function returns the indices that would sort the array
print("Indices that would sort the unsorted array:", np.argsort(unsorted_arr))
print("Indices that would sort the string array:", np.argsort(arr_strings))
print("Indices that would sort the float array:", np.argsort(arr_float))



Sorted Array: [  1   3  10  10  20  30  40  50  99 100]
Original Unsorted Array: [ 50  20  40  10  30  10   3   1 100  99]
Sorted String Array: ['apple' 'banana' 'cherry' 'date']
Original String Array: ['banana' 'apple' 'cherry' 'date']
Sorted Float Array: [1.2 2.4 3.1 4.8 5.6]
Original Float Array: [3.1 2.4 5.6 1.2 4.8]
Indices that would sort the unsorted array: [7 6 3 5 1 4 2 0 9 8]
Indices that would sort the string array: [1 0 2 3]
Indices that would sort the float array: [3 1 0 4 2]


## Sorting on 2D-Array

In [7]:
unsorted_arr_2d = np.array([[30, 10, 20],
                            [60, 50, 40],
                            [90, 80, 70]], dtype="int32")

print("2D Array Sorted by Rows:\n", np.sort(unsorted_arr_2d, axis=1))

print("2D Array Sorted by Columns:\n", np.sort(unsorted_arr_2d, axis=0))

print("2D Array Original:\n", unsorted_arr_2d)

print("Indices that would sort each row:\n", np.argsort(unsorted_arr_2d, axis=1))
print("Indices that would sort each column:\n", np.argsort(unsorted_arr_2d, axis=0))

# the .sort() and .argsort() functions can sort along specified axes in multi-dimensional arrays
# axis=0 sorts along columns, axis=1 sorts along rows
# the original array remains unchanged after sorting operations

2D Array Sorted by Rows:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
2D Array Sorted by Columns:
 [[30 10 20]
 [60 50 40]
 [90 80 70]]
2D Array Original:
 [[30 10 20]
 [60 50 40]
 [90 80 70]]
Indices that would sort each row:
 [[1 2 0]
 [2 1 0]
 [2 1 0]]
Indices that would sort each column:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


<div><h1 style = "color:cyan"><b>Numpy Array Operation: FILTERATION</h1><div>

In [9]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype="int32")
print("Original Array:", numbers)

squared_numbers = np.square(numbers)
print("Squared Array:", squared_numbers)

cube_numbers = np.power(numbers, 3)
print("Cubed Array:", cube_numbers)

add_five = np.add(numbers, 5)
print("Array after Adding 5:", add_five)

multiply_by_two = np.multiply(numbers, 2)
print("Array after Multiplying by 2:", multiply_by_two)

divide_by_three = np.divide(numbers, 3)
print("Array after Dividing by 3:", divide_by_three)

mod_three = np.mod(numbers, 3)
print("Array after Modulus 3:", mod_three)

# MOST IMPORTANTLY: Using NumPy's vectorized operations 
# for element-wise computations is significantly faster than 
# using traditional loops in Python.

even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers Array:", even_numbers)




Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Squared Array: [  1   4   9  16  25  36  49  64  81 100]
Cubed Array: [   1    8   27   64  125  216  343  512  729 1000]
Array after Adding 5: [ 6  7  8  9 10 11 12 13 14 15]
Array after Multiplying by 2: [ 2  4  6  8 10 12 14 16 18 20]
Array after Dividing by 3: [0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
Array after Modulus 3: [1 2 0 1 2 0 1 2 0 1]
Even Numbers Array: [ 2  4  6  8 10]


# Filter with MASK

In [11]:
# What is MASKING in NumPy?

# Masking in NumPy refers to the technique of using boolean arrays 
# to filter or select elements from another array based on certain conditions. 
# A mask is essentially an array of the same shape as the original array, 
# where each element is either True or False. When you apply this mask to the 
# original array, only the elements corresponding to True values 
# in the mask are selected.

# This technique is particularly useful for data analysis and manipulation, 
# as it allows for efficient filtering of large datasets without the need for explicit loops.

data = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50], dtype="int32")
print("Original Data Array:", data)

mask = data > 25 # simply a condition that generates a boolean array
print("Mask (data > 25):", mask)

printed_data = data[mask]
print("Filtered Data (data > 25):", printed_data)

Original Data Array: [10 15 20 25 30 35 40 45 50]
Mask (data > 25): [False False False False  True  True  True  True  True]
Filtered Data (data > 25): [30 35 40 45 50]


## Filter With WHERE clause

In [14]:
data = np.array([10, 25, 30, 35, 40, 45, 50], dtype="int32")
print("Original Data Array:", data)

where_mask = np.where(data % 20 == 0)
print("Indices where data is divisible by 20:", where_mask)
filtered_data = data[where_mask]
print("Filtered Data (divisible by 20):", filtered_data)

# where() accepts three arguments: condition, x, y
# It returns elements chosen from x or y depending on the condition.
# EXAMPLE:
#  IF(CONDITION){
#    DO SOMETHING
# } ELSE {
#    DO SOMETHING
# }

data = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50], dtype="int32")
print("Original Data Array:", data)
modified_data = np.where(data % 2 == 0, data * 2, data + 5)
print("Modified Data (even * 2, odd + 5):", modified_data)

# Masking allows for efficient and flexible data selection and manipulation
# based on conditions, making it a powerful tool in NumPy for data analysis tasks.
# .Where() function can be used for conditional selection and modification of array elements.
# it is just like SQL's IF-ELSE statement.



Original Data Array: [10 25 30 35 40 45 50]
Indices where data is divisible by 20: (array([4]),)
Filtered Data (divisible by 20): [40]
Original Data Array: [10 15 20 25 30 35 40 45 50]
Modified Data (even * 2, odd + 5): [ 20  20  40  30  60  40  80  50 100]


<div><h1 style = "color:cyan"><b>Numpy Array Operation: <u><i>ADDING/REMOVING</u> Data</h1><div>

## Array Compability:

In [ ]:
# Before Performing any operation on NumPy arrays, it is crucial to ensure 
# that the arrays involved are compatible in terms of their shapes. 
# This compatibility is essential for successful broadcasting, 
# which allows NumPy to perform operations on arrays of different shapes 
# without explicitly reshaping them.

arr_a = np.array([[1, 2, 3],
                  [4, 5, 6]], dtype="int32")  # Shape (2, 3)

arr_b = np.array([10, 20, 30], dtype="int32")    # Shape (3,1)

result = arr_a + arr_b  # Broadcasting occurs here
print("Result of Broadcasting Addition:\n", result)
# Output:
# [[11 22 33]
#  [14 25 36]]
# In this example, arr_b is broadcasted across the rows of arr_a, 
# allowing for element-wise addition.

print("is arr_a and arr_b compatible for broadcasting?", np.shape(arr_a), "and", np.shape(arr_b), "->", np.broadcast_shapes(np.shape(arr_a), np.shape(arr_b)))
print("arr_a == arr_b ", arr_a.shape == arr_b.shape)  # Output: False

# What is BroadCasting and its internal working ?

# Broadcasting is a powerful mechanism in NumPy that allows for
# operations on arrays of different shapes. It works by "stretching"
# the smaller array across the larger one so that they have compatible shapes.

# The rules of broadcasting are as follows:

# 1. If the arrays have a different number of dimensions,
#    the shape of the smaller-dimensional array is padded with ones
#    at the beginning until both arrays have the same number of dimensions.

# 2. For each dimension, if the size of one array is 1, it is stretched to match
#    the size of the other array in that dimension.

# 3. If neither array has a size of 1 in a particular dimension, and their sizes differ,
#    then broadcasting fails with an error.

merged_arr = np.concatenate((arr_a, arr_b))


Result of Broadcasting Addition:
 [[11 22 33]
 [14 25 36]]
is arr_a and arr_b compatible for broadcasting? (2, 3) and (3,) -> (2, 3)
arr_a == arr_b  False


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [34]:
merged_arr_corrected = np.vstack((arr_a, arr_b))
print("Merged Array using vstack(row-wise):\n", merged_arr_corrected)


reshaped_arr_b = arr_b.reshape(-1, 1)  # Reshape arr_b for compatibility
# Reshaping arr_b to (3, 1) to match arr_a's transposed shape (3, 2)
merged_arr_corrected = np.hstack((arr_a.T, reshaped_arr_b))
print("Merged Array using hstack(column-wise):\n", merged_arr_corrected)


a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype="int32")  # Shape (2, 3)

b = np.array([[10],
              [20]], dtype="int32")    # Shape (2, 1)

c = np.array([[10, 20, 30]], dtype="int32")    # Shape (1, 3)

print("with new column: ", np.hstack((a, b)))  # Shape (2, 4)
print("with new row: ", np.vstack((a, c)))  # Shape (3, 3)





Merged Array using vstack(row-wise):
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
Merged Array using hstack(column-wise):
 [[ 1  4 10]
 [ 2  5 20]
 [ 3  6 30]]
with new column:  [[ 1  2  3 10]
 [ 4  5  6 20]]
with new row:  [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


## Removing the data

In [36]:
original_arr = np.array([1, 2, 3, 4, 5], dtype="int32")
print("Original Array:", original_arr)

deleted = np.delete(arr=original_arr, obj=2)  # Remove element at index 2
print("Array after Deletion:", original_arr)
print("Deleted Element:", deleted)



Original Array: [1 2 3 4 5]
Array after Deletion: [1 2 3 4 5]
Deleted Element: [1 2 4 5]
