## Introduction To Numpy

In [2]:
import numpy as np

<div><h1 style="color:teal"><b>Creating Array from list </h1></div>

In [3]:
# Create a 1D array of integers with specified values and data type

# content: [1, 2, 3, 4, 5], data type: int32
# instruction: Use np.array with object and dtype parameters

arr_1d = np.array(object=[1, 2, 3, 4, 5], dtype=np.int32)

# Create a 2D array of integers with specified values and data type
# content: [[1, 2, 3], [4, 5, 6]], data type: int32
# instruction: Use np.array with object and dtype parameters
arr_2d = np.array(object=[[1, 2, 3], [4, 5, 6]], dtype=np.int32)


#Create a 1D array of strings with specified values and data type
# content: ['apple', 'banana', 'cherry'], data type: U10
# instruction: Use np.array with object and dtype parameters
# data type U10 means Unicode string with a maximum length of 10 characters

arr_str = np.array(object=['apple', 'banana', 'cherry'], dtype='U10')

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
print("String Array:", arr_str)



1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
String Array: ['apple' 'banana' 'cherry']


<div><h1 style="color:teal"><b>Numpy Arrays vs Python List </h1></div>

In [4]:
py_list = [10, 20, 30, 40, 50]
print("Python List Multiplication: ", py_list*2)

np_array = np.array(object=py_list, dtype=np.int32)
print("NumPy Array Multiplication: ", np_array*2)

# Summary:

# The Python list concatenates itself, while the NumPy array performs element-wise multiplication.
# This showcases the powerful capabilities of NumPy for numerical computations.

# Why NumPy?

# NumPy is a powerful library for numerical computing in Python. It provides support for large,
# multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
# Key advantages of using NumPy include:

# 1. Performance: NumPy arrays are more efficient in terms of memory and speed compared to standard Python lists,
#    especially for large datasets and complex mathematical operations.

# 2. Functionality: NumPy offers a wide range of built-in functions for mathematical operations, statistical analysis, linear algebra, and more.

# 3. Ease of Use: NumPy provides a simple and intuitive syntax for array manipulation and mathematical computations, making it easier to write and read code.

# 4. Integration: NumPy integrates well with other scientific computing libraries in Python, such as SciPy, Pandas, and Matplotlib,
#    making it a fundamental tool for data analysis and scientific computing.

Python List Multiplication:  [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
NumPy Array Multiplication:  [ 20  40  60  80 100]


### Python List vs Numpy array time

In [5]:
import time
size = 1000000

py_list = list(range(size))
print(py_list[:10])  # Print first 10 elements for verification

start_time = time.time()
py_list_squared = [x**2 for x in py_list]
end_time = time.time()
print("Python List Squaring Time: {:.6f} seconds".format(end_time - start_time))

np_array = np.array(object=py_list, dtype=np.int32)
start_time = time.time()
np_array_squared = np_array**2
end_time = time.time()
print("NumPy Array Squaring Time: {:.6f} seconds".format(end_time - start_time))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Python List Squaring Time: 0.110221 seconds
NumPy Array Squaring Time: 0.001932 seconds


<div><h1 style="color:teal"><b>Making Array from scratch</h1></div>

### Rules of Numpy Arrays:
<ol>
<li>All elements of the array must be of the same type of data.
<li>Once created, the total size of the array can’t change.
<li>The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.
</ol>

In [6]:
# For making arrays from scratch, we can use functions like np.zeros, np.ones, and np.eye. etc ...
# These functions allow us to create arrays filled with zeros, ones, or identity matrices, respectively.
# shape parameter defines the dimensions of the array, and dtype specifies the data type of the elements.

zero = np.zeros(shape=(3, 4), dtype=np.float32) # it creates a 3x4 array filled with zeros of float type

one = np.ones(shape=(2, 5), dtype=np.int32) # it creates a 2x5 array filled with ones of integer type

identity = np.eye(N=4, M=4, dtype=np.int32) # it creates a 4x4 identity matrix of integer type

range_array = np.arange(start=0, stop=10, step=2, dtype=np.int32) # it creates a 1D array with values from 0 to 10 with a step of 2

random_array = np.random.rand(3, 3) # it creates a 3x3 array with random float values between 0 and 1

random_int_array = np.random.randint(low=0, high=100, size=(2, 4), dtype=np.int32) # it creates a 2x4 array with random integer values between 0 and 100



print("Zero Array:\n", zero)
print("One Array:\n", one)
print("Identity Matrix:\n", identity)
print("Range Array:", range_array)
print("Random Float Array:\n", random_array)
print("Random Integer Array:\n", random_int_array)



Zero Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Identity Matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Range Array: [0 2 4 6 8]
Random Float Array:
 [[0.13453748 0.08720989 0.36482555]
 [0.51738465 0.77930955 0.93490878]
 [0.2281654  0.67971123 0.19371967]]
Random Integer Array:
 [[44 47 34 21]
 [45 25 30 64]]


<div><h1 style="color:teal"><b>Vector, Matrices and Tensor:</h1></div>

In [7]:
vector = np.array(object=[1, 2, 3], dtype=np.int32)  # 1D array
matrix = np.array(object=[[1, 2, 3], 
                          [4, 5, 6]], dtype=np.int32)  # 2D array
tensor = np.array(object=[
        [[1, 2], [3, 4]], 
        [[5, 6], [7, 8]]
    ], dtype=np.int32)  # 3D array or N-Dimensional array

# Tensor is a multi-dimensional array that generalizes the concepts of scalars (0D), vectors (1D), and matrices (2D) to higher dimensions.

print("Vector (1D Array):", vector)
print("Matrix (2D Array):\n", matrix)
print("Tensor (3D Array):\n", tensor)



Vector (1D Array): [1 2 3]
Matrix (2D Array):
 [[1 2 3]
 [4 5 6]]
Tensor (3D Array):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<div><h1 style="color:teal"><b>Array Properties</h1></div>

In [8]:
np_array = np.array(object=[[1, 2, 3], [4, 5, 6]], dtype=np.int32)

print("Shape of the array:", np_array.shape)
# The shape attribute returns a tuple representing the dimensions of the array.

print("Number of dimensions:", np_array.ndim)
# The ndim attribute returns the number of dimensions (axes) of the array.

print("Data type of the array elements:", np_array.dtype)
# The dtype attribute returns the data type of the elements in the array.

print("Size of each element in bytes:", np_array.itemsize)
# The itemsize attribute returns the size (in bytes) of each element in the array.

print("Total number of elements in the array:", np_array.size)
# The size attribute returns the total number of elements in the array.

print("Total memory consumed by the array in bytes:", np_array.nbytes)
# The nbytes attribute returns the total number of bytes consumed by the array's data.

print("Array contents:\n", np_array)
# Finally, we print the contents of the array itself.





Shape of the array: (2, 3)
Number of dimensions: 2
Data type of the array elements: int32
Size of each element in bytes: 4
Total number of elements in the array: 6
Total memory consumed by the array in bytes: 24
Array contents:
 [[1 2 3]
 [4 5 6]]
